

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# jobs中每个job都是独立的一个虚拟环境，jobs之间是并行运行的
jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # 安装msys 这样windows编译环境就可以直接使用shell脚本
    - name: Install msys
      uses: msys2/setup-msys2@v2  

    - name: Run build
      run: |
        cd script
        bash ./build_ci.sh

    - name: Upload production-ready build files
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: v2ray_r.exe
        path: user-end/target/release/v2ray_r.exe



