

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 手动触发

# jobs中每个job都是独立的一个虚拟环境，jobs之间是并行运行的
jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v3

    - name: Install Yarn via npm
      run: npm install -g yarn

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # 安装msys 这样windows编译环境就可以直接使用shell脚本
    - name: Install msys
      uses: msys2/setup-msys2@v2  
      with:
        update: true
        install: >
          zip
      
    - name: Add MSYS2 to PATH
      run: echo "C:\msys64\usr\bin" >> $GITHUB_PATH

    - name: Run build
      run: |
        cd script
        bash ./build_ci.sh

    - name: Upload production-ready build files
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: v2ray_r-win # 文件夹名称
        path: user-end/target/release/v2ray_r.exe



